#!/bin/sh

PROJECT="$(dirname $PWD/..)"
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD |grep -v 'xHTML/' | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in $SFILES
do
    php -l -d display_errors=0 $PROJECT/$FILE
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
    echo "Running Code Sniffer. Code standard Symfony."
    ./vendor/bin/phpcs --standard=Symfony --colors --encoding=utf-8 -n -p $FILES
    if [ $? != 0 ]
    then
        echo "Fix the error before commit!"
        echo "Run"
        echo "  ./vendor/bin/phpcbf --standard=Symfony $FILES"
        echo "for automatic fix or fix it manually."
        exit 1
    fi
fi

exit $?
