#!/bin/sh

PROJECT="$(dirname $PWD/..)"
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD |grep -v 'xHTML/' | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

if [ "$FILES" != "" ]
then
    echo "Running Code Sniffer. Code standard Symfony."
    make check
    if [ $? != 0 ]
    then
        echo "Fix the error before commit!"
        exit 1
    fi
fi

exit $?

